"""Persistent bootstrap state and first-run setup for appliance installations."""

import hashlib
import json
import os
import platform
import secrets
from datetime import datetime, timezone
from pathlib import Path


def config_root() -> Path:
    return Path(os.getenv("CONFIG_ROOT", "/data/config"))


def _read(name: str, default: dict | None = None) -> dict:
    try:
        value = json.loads((config_root() / name).read_text(encoding="utf-8"))
        return value if isinstance(value, dict) else (default or {})
    except (OSError, ValueError):
        return default or {}


def _write(name: str, value: dict) -> None:
    root = config_root()
    root.mkdir(parents=True, exist_ok=True)
    path = root / name
    temporary = root / f".{name}.tmp"
    temporary.write_text(json.dumps(value, ensure_ascii=False, indent=2), encoding="utf-8")
    os.chmod(temporary, 0o600)
    temporary.replace(path)


def password_hash(value: str) -> str:
    salt = secrets.token_hex(16)
    iterations = 310_000
    digest = hashlib.pbkdf2_hmac("sha256", value.encode(), salt.encode(), iterations).hex()
    return f"pbkdf2_sha256${iterations}${salt}${digest}"


def ensure_secret_store() -> dict:
    stored = _read("secrets.json")
    if stored:
        return stored
    stored = _read("bootstrap-secrets.json")
    generated = {name: secrets.token_urlsafe(size) for name, size in {
        "jwt_secret": 48, "worker_secret": 48, "encryption_key": 32,
        "internal_api_key": 48, "session_secret": 48}.items()}
    stored = {**generated, **stored}
    # Database/Redis credentials are generated by bootstrap before those services start.
    stored["created_at"] = datetime.now(timezone.utc).isoformat()
    _write("secrets.json", stored)
    (config_root() / "bootstrap-secrets.json").unlink(missing_ok=True)
    return stored


def installation() -> dict:
    return _read("installation.json")


def is_configured() -> bool:
    # Existing source installations remain usable; appliance installs explicitly set CONFIG_ROOT.
    if "CONFIG_ROOT" not in os.environ:
        return True
    return bool(installation().get("completed_at"))


def runtime_hardware() -> dict:
    detected = _read("hardware.json")
    return {"architecture": platform.machine(), "cpu_count": os.cpu_count(),
            "ram_mb": detected.get("ram_mb"), "gpu": detected.get("gpu", {"vendor": "none"}),
            **{key: value for key, value in detected.items() if key not in {"ram_mb", "gpu"}}}


def setup_status() -> dict:
    ensure_secret_store()
    return {"configured": is_configured(), "installation": installation() if is_configured() else None,
            "hardware": runtime_hardware(),
            "backends": ["ollama", "openai", "external", "skip"],
            "selected_role": os.getenv("NODE_ROLE") if os.getenv("NODE_ROLE") not in {None, "unassigned"} else None}


def complete_setup(name: str, username: str, password: str, confirmation: str,
                   backend: str, backend_url: str | None = None, node_role: str = "core",
                   core_url: str | None = None, node_credentials: dict | None = None) -> dict:
    if is_configured():
        raise FileExistsError("First-run setup has already been completed")
    if not name.strip() or len(name.strip()) > 120:
        raise ValueError("Installation name must contain 1-120 characters")
    if not username.replace("_", "").replace("-", "").isalnum() or not 3 <= len(username) <= 64:
        raise ValueError("Administrator login must contain 3-64 letters, numbers, '_' or '-'")
    if password != confirmation:
        raise ValueError("Password confirmation does not match")
    if len(password) < 12:
        raise ValueError("Administrator password must contain at least 12 characters")
    if backend not in {"ollama", "openai", "external", "skip"}:
        raise ValueError("Unsupported AI backend")
    from .node_registry import node_roles
    roles = node_roles()
    if node_role not in roles:
        raise ValueError("Unsupported node role")
    selected_role = os.getenv("NODE_ROLE")
    if selected_role not in {None, "unassigned", node_role}:
        raise ValueError(f"Bootstrap deployment plan is locked to role {selected_role}")
    if node_role != "core" and (not core_url or not node_credentials):
        raise ValueError("A non-Core node must be registered with Core")
    secrets_store = ensure_secret_store()
    value = {"installation_id": secrets.token_hex(16), "installation_name": name.strip(),
             "version": os.getenv("VERTEP_VERSION", "unknown"), "created_at": datetime.now(timezone.utc).isoformat(),
             "completed_at": datetime.now(timezone.utc).isoformat(), "hardware": runtime_hardware(),
             "node_role": node_role, "modules": roles[node_role]["modules"],
             "core_url": core_url if node_role != "core" else None,
             "worker_count": int(os.getenv("BOOTSTRAP_WORKER_COUNT", "0")),
             "ai_backend": {"type": backend, "url": backend_url},
             "administrator": {"username": username, "password_hash": password_hash(password), "role": "admin"}}
    _write("installation.json", value)
    if node_credentials:
        _write("node-credentials.json", node_credentials)
    return {key: item for key, item in value.items() if key != "administrator"} | {
        "administrator": {"username": username, "role": "admin"},
        "session_secret_ready": bool(secrets_store.get("session_secret"))}


def configured_user() -> tuple[str, dict] | None:
    admin = installation().get("administrator")
    return (admin.get("username"), admin) if isinstance(admin, dict) else None


def session_secret() -> str:
    if "CONFIG_ROOT" not in os.environ:
        return os.getenv("ADMIN_PASSWORD", "")
    return str(ensure_secret_store().get("session_secret", ""))
